In [1]:
import numpy as np

In [2]:
#np.array():creates an numpy array
a=np.array([3,7,9,5,6])
print(a)


[3 7 9 5 6]


In [3]:
#np.zeros():Creates an array filled with zeros
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [4]:
#np.ones():Creates an array filled with ones
arr=np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [5]:
#np.empty():Creates an empty array
b=np.empty(4)
print(arr)

[1. 1. 1. 1.]


In [6]:
#np.arange():Creates an array with a range of values
arr=np.arange(10,99,60)
print(arr)

[10 70]


In [7]:
#np.full():Creates an array filled with a specified value
arr=np.full((2,21),2)
print(arr)

[[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]


In [8]:
#np.linspace():Creates an array with a specified number of evenly spaced values between a given range
arr=np.linspace(6,10,7)
print(arr)

[ 6.          6.66666667  7.33333333  8.          8.66666667  9.33333333
 10.        ]


In [9]:
#np.logspace():Creates an array with a specified number of logarithmically spaced values between a given range
a = np.logspace(1, 52, 3)
print(a)

[1.00000000e+01 3.16227766e+26 1.00000000e+52]


In [10]:
#np.identity():Creates an square identity matrix
arr=np.identity(10)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [11]:
#np.reshape():Reshapes an array to a specified shape
a = np.array([1, 2, 3, 4, 5, 6])
b = np.reshape(a, (2, 3))
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
#np.ravel():Converts a multidimensional array into a 1-D array
a = np.array([[20,52], [33, 94]])
print(np.ravel(a))


[20 52 33 94]


In [13]:
#np.transpose():interchanges the rows and columns of an array
a = np.array([[1, 2], [3, 4]])
print(np.transpose(a))

[[1 3]
 [2 4]]


In [14]:
#np.resize():changes the size of an array
a = np.array([1, 2, 3])
print(np.resize(a, 6))

[1 2 3 1 2 3]


In [15]:
#np.append():Appends values to the end of an array
a = np.array([1, 2, 3])
c = np.append(a,20)
print(c)

[ 1  2  3 20]


In [16]:
#np.insert():Inserts values into an array at a specified index
a = np.array([1, 2, 3])
b = np.insert(a, 1, 5)
print(b)

[1 5 2 3]


In [17]:
#np.delete():deletes values from an array at a specified index
a = np.array([1, 2, 3])
b = np.delete(a, 2)
print(b)

[1 2]


In [18]:
#np.concatenate():joins two or more arrays along a specified axis
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
print(c)


[[1 2]
 [3 4]
 [5 6]]


In [19]:
#np.stack():Stacks arrays along a specified axis
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.stack((a, b), axis=0)
print(c)


[[1 2 3]
 [4 5 6]]


In [20]:
#np.vstack():Stacks arrays vertically (row-wise)
a = np.array([1, 2])
b = np.array([3, 4])

print(np.vstack((a, b)))

[[1 2]
 [3 4]]


In [21]:
#np.hstack():Stacks arrays horizontally (column-wise)
a = np.array([1, 2])
b = np.array([3, 4])

print(np.hstack((a, b)))

[1 2 3 4]


In [22]:
#np.dstack():Stacks arrays depth-wise 
a = np.array([1, 2])
b = np.array([3, 4])

print(np.dstack((a, b)))

[[[1 3]
  [2 4]]]


In [23]:
#np.spilt():Splits an array into multiple sub-arrays along a specified axis
a = np.array([1, 2, 3, 4, 5, 6,7,8,9])

print(np.split(a, 3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [24]:
#np.array_split():spilts an array even when equal division is not possiblea = np.array([1, 2, 3, 4, 5])
a = np.array([1, 2, 3, 4, 5])

print(np.array_split(a, 3))


[array([1, 2]), array([3, 4]), array([5])]


In [25]:
#np.hsplit():spilts an array into multiple sub-arrays horizontally (column-wise)
a = np.array([1, 2, 3, 4,5,5])

print(np.hsplit(a, 2))

[array([1, 2, 3]), array([4, 5, 5])]


In [26]:
#np.vsplit():spilts an array into multiple sub-arrays vertically (row-wise)
a = np.array([[1, 2], [3, 4]])

print(np.vsplit(a, 2))

[array([[1, 2]]), array([[3, 4]])]


In [27]:
#np.flip():reverses the order of elements in an array along a specified axis
a = np.array([1, 2, 3, 4])

print(np.flip(a))

[4 3 2 1]


In [28]:
#np.add(): Adds corresponding elements of two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.add(a, b))

[5 7 9]


In [29]:
#np.subtract(): Subtracts corresponding elements of two arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(np.subtract(a, b))

[ 9 18 27]


In [30]:
#np.multiply(): Multiplies corresponding elements of two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.multiply(a, b))

[ 4 10 18]


In [31]:
#np.divide(): Divides corresponding elements of two arrays
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print(np.divide(a, b))

[5. 5. 6.]


In [32]:
#np.power():raises number to a power
a = np.array([2, 3, 4])

print(np.power(a, 2))

[ 4  9 16]


In [33]:
#np.mod():returns the remainder
a = np.array([10, 11, 12])

print(np.mod(a,5))

[0 1 2]


In [34]:
#np.sqrt():calculates the square roots
a = np.array([4, 9, 16, 25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [35]:
#np.exp():calculates the exponential values
a = np.array([1, 2, 3])
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [36]:
#np.log():calculates the natural logarithms
a = np.array([1, 2, 10])
print(np.log(a))

[0.         0.69314718 2.30258509]


In [37]:
#np.abs():calculates the absolute values
a = np.array([-10, -5, 3, -2])
print(np.abs(a))

[10  5  3  2]


In [38]:
#np.sum():calculates the sum of array elements
a = np.array([10, 20, 30, 40])

print(np.sum(a))


100


In [39]:
 #np.mean():calculates the arithemetic mean
a = np.array([10, 20, 30, 40])

print(np.mean(a))


25.0


In [40]:
#np.median()
a = np.array([10, 20, 30, 40, 50])

print(np.median(a))

30.0


In [41]:
#np.std():calculates the standard deviation
a = np.array([10, 20, 30, 40])

print(np.std(a))


11.180339887498949


In [42]:
#np.var():calculates the variance
a = np.array([10, 20, 30, 40])

print(np.var(a))

125.0


In [43]:
#np.min():calculates the minimum value
a = np.array([50, 20, 80, 10, 40])

print(np.min(a))

10


In [44]:
#np.max():calculates the maximum value
a = np.array([50, 20, 80, 10, 40])

print(np.max(a))

80


In [45]:
#np.sort():sorts an array
a = np.array([40, 10, 30, 20])

print(np.sort(a))

[10 20 30 40]


In [46]:
#p.argsort():returns the indices that would sort an array
a = np.array([40, 10, 30, 20])

print(np.argsort(a))


[1 3 2 0]


In [47]:
#np.argmax():returns the index of the maximum value
a = np.array([10, 50, 20, 80, 30])

print(np.argmax(a))


3


In [48]:
#np.argmin():returns the index of the minimum value
a = np.array([10, 50, 5, 80, 30])

print(np.argmin(a))

2


In [49]:
#np.round():rounds the values in an array to the nearest integer
a = np.array([1.234, 2.567, 3.891])

print(np.round(a, 2))

[1.23 2.57 3.89]


In [50]:
#np.floor():rounds the values in an array down to the nearest integer
a = np.array([1.2, 2.8, 3.5])

print(np.floor(a))

[1. 2. 3.]


In [51]:
#np.ceil():rounds the values in an array up to the nearest integer
a = np.array([1.2, 2.8, 3.1])

print(np.ceil(a))

[2. 3. 4.]


In [52]:
#np.trunc():removes the decimal part of the values in an array
a = np.array([1.9, 2.5, 3.8])

print(np.trunc(a))


[1. 2. 3.]


In [53]:
#np.fix(): rounds the values in an array towards zero
a = np.array([2.9, -2.9])

print(np.fix(a))

[ 2. -2.]


In [54]:
#np.sin():calculates the sine of the values
a = np.array([0, np.pi/2, np.pi])
print(np.sin(a)) 


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [55]:
#np.unique():returns the unique values in an array
a = np.array([1, 2, 2, 3, 3, 4])

print(np.unique(a))


[1 2 3 4]


In [56]:
#np.intersect1d():returns the common values between two arrays
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print(np.intersect1d(a, b))

[3 4]


In [57]:
#np.union1d():returns the common values between two arrays
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

print(np.union1d(a, b))


[1 2 3 4 5]


In [58]:
#np.setdiff1d():finds the set difference of two arrays
a = np.array([1, 2, 3, 4])
b = np.array([3, 4])

print(np.setdiff1d(a, b))

[1 2]


In [59]:
# np.equal(): Checks if elements are equal
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])
print(np.equal(a, b))


[ True  True False]


In [60]:
#np.not_equal:checks if elements are not equal
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])
print(np.not_equal(a, b))

[False False  True]


In [61]:
#np.greater():checks if elements of one array are greater than the other
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(np.greater(a, b)) 

[False False  True]


In [62]:
#np.greater():checks if elements of one array are greater than the corresponding elements of another array
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(np.greater(a, b))


[False False  True]


In [63]:
#np.less():checks if elements of one array are less than the corresponding elements of another array
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(np.less(a, b))


[ True False False]


In [64]:
#np.resize():changes the size of an array
a = np.array([1, 2, 3])
print(np.resize(a, 6))


[1 2 3 1 2 3]


In [65]:
#np.squeeze():removes single-dimensional entries from the shape of an array
a = np.array([[[1], [2], [3]]])
print(np.squeeze(a))
    

[1 2 3]


In [66]:
#np.poly():Creates a polynomial from its roots
a = np.array([1, 2, 3])
print(np.poly(a))


[ 1. -6. 11. -6.]


In [67]:
#np.polyval():Evaluates a polynomial at specific values
p = [1, -5, 6]

print(np.polyval(p, 2))

0


In [68]:
#np.polyfit():Fits a polynomial of a specified degree to data
x = np.array([1, 2, 3, 4])
y = np.array([1, 4, 9, 16])

coeff = np.polyfit(x, y, 2)

print(coeff)

[ 1.00000000e+00 -4.50610017e-15  6.10781269e-15]


In [69]:
#np.polyder():Computes the derivative of a polynomial
p = [1, -5, 6]

print(np.polyder(p))

[ 2 -5]


In [70]:
#np.polyint():Finds the integral of a polynomial
p = [2, 3]

print(np.polyint(p))

[1. 3. 0.]


In [71]:
#np.roots():Finds the roots of a polynomial
p = [1, -5, 6]

print(np.roots(p))

[3. 2.]


In [72]:
#np.polyadd():Adds two polynomials
p1 = [1, 2]
p2 = [3, 4]

print(np.polyadd(p1, p2))

[4 6]


In [73]:
#np.polysub():Subtracts two polynomials
p1 = [5, 7]
p2 = [2, 3]

print(np.polysub(p1, p2))

[3 4]


In [74]:
#np.polymul():Multiplies two polynomials
p1 = [1, 2]
p2 = [3, 4]
print(np.polymul(p1, p2))

[ 3 10  8]


In [75]:
#np.polydiv():Divides two polynomials
p1 = [1, 5, 6]
p2 = [1, 2]

q, r = np.polydiv(p1, p2)

print("Quotient:", q)
print("Remainder:", r)

Quotient: [1. 3.]
Remainder: [0.]
